chatapp/chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.index, name='index'),
    path('post', views.post, name='post'),
]

chatapp/chatapp/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('chat.urls')),
    path('admin/', admin.site.urls),
]

chatapp/chat/models.py
from django.db import models


class Message(models.Model):
    contents = models.CharField(max_length=80)
    response = models.TextField()
    created_at = models.DateTimeField()

    def __str__(self):
        return self.contents

chatapp/chat/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
import openai

from .models import Message


def index(request):
    messages = Message.objects.order_by('-created_at').reverse()
    context = {'messages': messages}
    return render(request, 'chat/index.html', context)


def post(request):
    openai.api_key = ''

    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {
                "role": "system",
                "content": "use english"
            },
            {
                "role": "user",
                "content": request.POST['contents']
            },
        ]
    )
    results = response["choices"][0]["message"]["content"]

    Message.objects.create(
        contents=request.POST['contents'],
        response=results,
        created_at=timezone.now()
    )
    return redirect('chat:index')

chatapp/chat/templates/chat/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>chat</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<div class="line__container">
    <div class="line__title">
        山田太郎
    </div>
    <div class="line__contents scroll">
        {% for message in messages %}
        <div class="line__right">
            <div class="text">{{ message.contents }}</div>
            <span class="date">既読<br>0:30</span>
        </div>
        <div class="line__left">
            <figure>
                <img src="{% static 'images/21.png' %}"/>
            </figure>
            <div class="line__left-text">
                <div class="name">山田太郎</div>
                <div class="text">{{message.response}}</div>
            </div>
        </div>
        {% endfor %}

        <div class="line__form-container">
            <form class="line__form" action="{% url 'chat:post' %}" method="post">
                {% csrf_token %}
                <input class="line__input" size="20" type="text" name="contents" required>
                <input class="line__submit" type="submit" value="→">
            </form>
        </div>

    </div>
</div>

</body>
</html>